### ISSUE TITLE
数据源

### ISSUE THREAD

**Issue by Frank-Hou** [haoruilee/AI-Preference-Selection#1]
请问一下这个的推荐问卷调查的数据源是哪里获得？

**Comment by haoruilee** [comment]
你好，推荐问卷是以当场测试的形式提供给用户的，位置在  rec2020/ UIdocs / 专业测试小游戏

**Comment by Frank-Hou** [comment]
> 你好，推荐问卷是以当场测试的形式提供给用户的，位置在 UIdocs / 专业测试小游戏

好的，十分感谢解答
