### ISSUE TITLE
你好，那个Django的高考志愿智能推荐系统的我遇到了问题方便解答吗

### ISSUE THREAD

**Issue by xiaosheng1999** [haoruilee/AI-Preference-Selection#2]
高考志愿智能推荐系统里的大学信息.csv文件损坏了，方便传个那个源文件给我吗

**Comment by haoruilee** [comment]
> 高考志愿智能推荐系统里的大学信息.csv文件损坏了，方便传个那个源文件给我吗

你好，我查看了一下没有找到你说的损坏文件，方便附上损坏文件的连接吗

**Comment by xiaosheng1999** [comment]
[大学信息.csv](https://github.com/haoruilee/AI-Preference-Selection/files/6839179/default.csv)

是这个文件，麻烦了

**Comment by haoruilee** [comment]
更新了，见 [a302f8](https://github.com/haoruilee/AI-Preference-Selection/commit/a302f8f9a69df61baace0991ca679b62f26cdfb7)
